### ISSUE TITLE
Known Issue: Not working with the latest PowerToys

### ISSUE THREAD

**Issue by SunsetMkt** [A-Archives-and-Forks/IzaiahSun-Community.PowerToys.Run.Plugin.Everything#4]
I'm sorry but could do nothing.
This Repo is just a fork of https://github.com/IzaiahSun/PowerToys .
@IzaiahSun did all the work and I just put the binary here.
Please contact @IzaiahSun or fix the plugin with @IzaiahSun 's source code.

**Comment by lwd-temp** [comment]
This Repo seems to have fixed this problem.
https://github.com/lin-ycv/EverythingPowerToys
